main: rippin.bullyscraft.com.FactionsMissions
author: RlPN/Rippin
version: 0.1
description: Missions for BullysCraft.
name: FactionsMissions
depend: [WorldEdit, WorldGuard]
softdepend: [Clearlagg, AsyncWorldEdit]
commands:
  bullymission:
    usage: Bully Mission Command.